### ISSUE TITLE
Documentation update required.

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-example-thread-statistics#56]
### Description

Following instructions on https://github.com/ARMmbed/mbed-os-example-thread-statistics/commit/a5bd65a5741fe0131007af272fb6db7c2537b483 doesn't result in working software.

After cloning and then following - https://github.com/ARMmbed/mbed-os-example-thread-statistics#building-and-running , the `mbed compile -m ARM_MUSCA_A1_NS -t GCC_ARM` fails.

It's missing `mbed import` or `mbed deploy .` instructions.
### Issue request type

[ ] Question  
[ ] Enhancement  
[ x] Bug

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCORE-1603*
